# Generated by Django 5.2 on 2025-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default='Curso indefinido', max_length=100),
            preserve_default=False,
        ),
    ]
