# Generated by Django 5.2 on 2025-06-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('nao_informado', 'Não Informar')], default='nao_informado', max_length=20)),
                ('cor', models.CharField(choices=[('pardo', 'Pardo'), ('branco', 'Branco'), ('preto', 'Preto'), ('amarelo', 'Amarelo'), ('indigena', 'Indígena')], default='pardo', max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('apadrinhado', models.BooleanField(default=False)),
                ('nivel_escolaridade', models.CharField(blank=True, choices=[('fundamental_completo', 'Fundamental Completo'), ('fundamental_incompleto', 'Fundamental Incompleto'), ('medio_completo', 'Médio Completo'), ('medio_incompleto', 'Ensino médio - Não finalizado'), ('superior_completo', 'Superior Completo'), ('superior_incompleto', 'Superior Incompleto')], max_length=50, null=True)),
                ('rede_ensino', models.CharField(blank=True, choices=[('publica', 'Rede pública (municipais/estadual/federal)'), ('privada', 'Rede privada')], max_length=20, null=True)),
                ('ano_periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('bolsista', models.BooleanField(default=False)),
                ('trabalha', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('autonomo', 'Autônomo'), ('estagiario', 'Estagiário'), ('desempregado', 'Desempregado')], max_length=20, null=True)),
                ('bairro_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('familia_participa', models.BooleanField(default=False)),
                ('media_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conhece_eca', models.CharField(blank=True, choices=[('sim', 'Sim'), ('ja_ouvi', 'Já ouvi falar'), ('nao', 'Não conheço')], max_length=20, null=True)),
                ('conselho_direito', models.CharField(blank=True, choices=[('sim', 'Sim'), ('ja_ouvi', 'Já ouvi falar'), ('nao', 'Não conheço')], max_length=20, null=True)),
                ('conselho_qual', models.CharField(blank=True, max_length=255, null=True)),
                ('forum_social', models.CharField(blank=True, choices=[('sim', 'Sim'), ('ja_ouvi', 'Já ouvi falar'), ('nao', 'Não conheço')], max_length=20, null=True)),
                ('nocao_direitos', models.CharField(blank=True, choices=[('sim_possuo', 'Sim, possuo.'), ('nao_sei', 'Não, não sei o que são.')], max_length=20, null=True)),
                ('referencia_familiar', models.CharField(blank=True, choices=[('positiva', 'Positiva.'), ('negativa', 'Negativa.')], max_length=20, null=True)),
                ('plano_saude', models.BooleanField(default=False)),
                ('qual_plano_saude', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanhamento_medico', models.BooleanField(default=False)),
                ('qual_problema_saude', models.CharField(blank=True, max_length=255, null=True)),
                ('cirurgia', models.BooleanField(default=False)),
                ('qual_cirurgia', models.CharField(blank=True, max_length=255, null=True)),
                ('deficiencia_fisica', models.BooleanField(default=False)),
                ('qual_deficiencia_fisica', models.CharField(blank=True, max_length=255, null=True)),
                ('deficiencia_mental', models.BooleanField(default=False)),
                ('doenca_transtorno', models.CharField(blank=True, choices=[('autismo', 'Autismo'), ('tdah', 'TDAH'), ('depressao', 'Depressão'), ('transtorno_bipolar', 'Transtorno Bipolar'), ('outro', 'Outro')], max_length=50, null=True)),
                ('refeicoes_dia', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5_mais', '5 ou mais')], max_length=10, null=True)),
                ('costuma_comer', models.CharField(blank=True, max_length=255, null=True)),
                ('participa_grupos', models.BooleanField(default=False)),
                ('qual_grupo_comunitario', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_moradia', models.CharField(blank=True, choices=[('propria', 'Própria'), ('alugada', 'Alugada'), ('cedida', 'Cedida'), ('outro', 'Outro')], max_length=20, null=True)),
                ('material_construcao', models.CharField(blank=True, choices=[('alvenaria', 'Alvenaria - Tijolos'), ('madeira', 'Madeira'), ('taipa', 'Taipa'), ('outro', 'Outro')], max_length=20, null=True)),
                ('vulnerabilidade_territorial', models.CharField(blank=True, max_length=255, null=True)),
                ('num_comodos', models.CharField(blank=True, choices=[('1_5', '1-5'), ('4_6', '4-6'), ('outro', 'Outro')], max_length=10, null=True)),
                ('outros_comodos', models.IntegerField(blank=True, null=True)),
                ('tem_banheiro', models.BooleanField(default=False)),
                ('banheiro_dentro_casa', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True)),
                ('energia_eletrica', models.BooleanField(default=False)),
                ('bens_possuidos', models.CharField(blank=True, max_length=255, null=True)),
                ('aquisicao_bens', models.CharField(blank=True, max_length=255, null=True)),
                ('condicao_bens', models.CharField(blank=True, max_length=255, null=True)),
                ('cadastro_unico', models.BooleanField(default=False)),
                ('bolsa_familia', models.BooleanField(default=False)),
                ('beneficio_bpc', models.BooleanField(default=False)),
                ('renda_familiar_total', models.CharField(blank=True, choices=[('ate_meio_sm', 'Até 1/2 Salário mínimo'), ('1_2sm', '1 a 2 Salários mínimos'), ('3_4sm', '3 a 4 Salários mínimos'), ('acima_4sm', 'Acima de 4 Salários mínimos')], max_length=20, null=True)),
                ('renda_per_capita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
