# Generated by Django 5.2 on 2025-05-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada do Curso')),
                ('idade_minima', models.IntegerField(blank=True, null=True, verbose_name='Idade Mínima Recomendada')),
                ('idade_maxima', models.IntegerField(blank=True, null=True, verbose_name='Idade Máxima Recomendada')),
                ('vagas_total', models.IntegerField(default=0, verbose_name='Número de Vagas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Curso Ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Processo Seletivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Processo Seletivo')),
                ('data_inicio_inscricoes', models.DateField(verbose_name='Início das Inscrições')),
                ('data_fim_inscricoes', models.DateField(verbose_name='Fim das Inscrições')),
                ('data_resultado', models.DateField(blank=True, null=True, verbose_name='Data do Resultado (Opcional)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Processo Ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cursos_oferecidos', models.ManyToManyField(related_name='processos_seletivos', to='processo_seletivo.curso', verbose_name='Cursos Disponíveis Neste Processo')),
            ],
            options={
                'verbose_name': 'Processo Seletivo',
                'verbose_name_plural': 'Processos Seletivos',
                'ordering': ['-data_inicio_inscricoes'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_crianca', models.CharField(max_length=255, verbose_name='Nome Completo da Criança')),
                ('data_nascimento_crianca', models.DateField(verbose_name='Data de Nascimento da Criança')),
                ('cpf_crianca', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF da Criança (Opcional)')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome Completo do Responsável')),
                ('cpf_responsavel', models.CharField(max_length=14, unique=True, verbose_name='CPF do Responsável')),
                ('email_responsavel', models.EmailField(max_length=254, verbose_name='E-mail do Responsável')),
                ('telefone_responsavel', models.CharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status da Inscrição')),
                ('observacoes_admin', models.TextField(blank=True, null=True, verbose_name='Observações do Administrador')),
                ('curso_escolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='processo_seletivo.curso', verbose_name='Curso Escolhido')),
                ('processo_seletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='processo_seletivo.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
                'unique_together': {('processo_seletivo', 'curso_escolhido', 'cpf_responsavel')},
            },
        ),
    ]
