# Generated by Django 5.2 on 2025-04-30 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('codigo_validacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='user.userprofile')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
