# Generated by Django 5.2 on 2025-04-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentacao', '0001_initial'),
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='frequencia.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('aluno', 'turma')},
        ),
    ]
