# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - lispector

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Certifique-se que esta é a versão correta para seu projeto

      - name: Create virtual environment
        run: python -m venv venv
      
      # CORREÇÃO AQUI: Ativa o venv antes de instalar
      - name: Install dependencies
        run: |
          source venv/bin/activate 
          pip install --upgrade pip
          pip install -r requirements.txt

      # CORREÇÃO AQUI: Garante que o venv está ativo
      - name: Collect static files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      # Optional: Add step to run tests here (PyTest, Django test suites, etc. )

      - name: Zip artifact for deployment
        # Inclui a pasta 'staticfiles' criada pelo collectstatic
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/ # Exclui a pasta venv do zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1FF2C04FDC134D0F9F9EAC4A090A7DCB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4981F1407688490BA8DE986FC1B098E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AFBE742213594740868030E66BF30814 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lispector'
          slot-name: 'Production'
          package: '.' # Indica que o conteúdo descompactado na raiz deve ser usado
